ChromHMM enhancer extension
biomedbigdata/TF-Prioritizer pull request #68
Opened 2023-12-01 14:48 UTC by LeonHafner

This pull request introduces the Enhancer Prediction with ChromHMM, as described in Issue #63.
The changes have not yet been tested and are not yet complete.

**TODO:**
- [ ] Add better way to create the cellmarkfiletable using the input csv for ehmm
- [ ] Add java container for BINARIZE_BAMS and LEARN_MODEL processes
- [ ] Get parameters from the config file (organism, genome version, ...)
- [ ] Add nf-core meta object to the input and output channels of the processes

2023-12-07 08:52 UTC, nictru commented on modules/local/ehmm/construct_model.nf
This change should not be part of this PR

2023-12-07 09:07 UTC, nictru commented on subworkflows/local/chromhmm.nf
Make sure indent in main is consistent

2023-12-07 09:09 UTC, nictru requested changes
Copy-pasting files from another repo is not a good practice, we should do one of the following:
- Reference files from there as Permalinks to the [original repo](https://github.com/jernst98/ChromHMM) directly in the igenomes config (preferable)
- Add the repo as git submodule

Resulting TODO list:
- [ ] Remove chromHMM files from this Repo
- [ ] Add meta entries to all processes, will contain metadata from the design file (state, assay) as well as a unique id (which should be added as tag to each process)
- [x] Add labels to each process (important for resource allocation)
- [x] Add java docker images: Even if it runs on our cluster, it does not have to run on every user's system
- I thought of something else and forgot it, will at later if it comes to my mind again

2023-12-07 15:12 UTC, LeonHafner commented on modules/local/ehmm/construct_model.nf
Just a note: We leave this commit in this PR, otherwise it will be missing in the merged version.

2023-12-26 20:52 UTC, LeonHafner commented
I integrated the ChromHMM workflow into the main pipeline and testet it.
This part should be done from my side and can be merged.
Feel free to make any necessary corrections before approving the merge.

2023-12-28 08:31 UTC, nictru requested changes
Implementation looks fine, but the ChromHMM output is not yet used in any way

2024-01-09 14:23 UTC, LeonHafner commented
I integrated the output of ChromHMM/Rose into the pipeline. This should finish the work on ChromHMM/Rose. Feel free to merge the PR or request further changes if needed.

2024-01-18 08:20 UTC, LeonHafner commented on conf/modules.config
> +    withName: SUBTRACT_BLACKLIST {
Had to add a config for this module due to a file name conflict

2024-01-24 12:45 UTC, nictru approved these changes

2024-01-24 12:45 UTC, merged